FROM node:lts-alpine


RUN npm install -g http-server

# make the 'app' folder the current working directory
WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .
COPY frontend.env ./.env

RUN npm run build

EXPOSE 8080
CMD [ "http-server", "dist" ]
