version: "3.9"

services:
  backend:
    build:
      context: ./backend  
      dockerfile: dockerfile  
    container_name: backend-container
    ports:
      - "4000:4000"
   

  frontend:
    build:
      context: ./frontend  
      dockerfile: dockerfile  
    container_name: frontend-container
    ports:
      - "8080:8080"
  
    depends_on:
      - backend  