FROM golang:1.19 AS build-stage

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY *.go ./

COPY backend.env ./.env

RUN go build -o /main

FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /main /main

COPY --from=build-stage /.env /.env

EXPOSE 4000

USER nonroot:nonroot

CMD [ "/main" ]
